// Generated by Convex
// This file contains type definitions for Convex functions

import { FunctionReference } from "convex/server";

export type Mutation = <Args extends any[], ReturnType>(
  func: (ctx: any, args: any) => ReturnType
) => FunctionReference<"mutation", Args, ReturnType>;

export type Query = <Args extends any[], ReturnType>(
  func: (ctx: any, args: any) => ReturnType
) => FunctionReference<"query", Args, ReturnType>;

export const mutation: Mutation;
export const query: Query;
