// Generated by Convex
// This file contains type definitions for Convex functions
// In a real project, this would be generated by `npx convex codegen`

export const mutation = (func) => func;
export const query = (func) => func;
